import { normalizeCompanyName } from "@yna/utils";
import type { ExpertMaster, PartnerMaster, StartupMaster } from "./types";

/**
 * Hub 마스터 원장 mock 시드 데이터(스타트업/전문가/협력사). (근거: 4_memo 이슈17·19·21)
 * 부속 테이블(식별자/별칭/이력/중복후보/감사)과 조립은 mock-seed.ts 에서 처리한다.
 */

function startup(
  partial: Omit<StartupMaster, "normalizedName" | "corporationNumber"> &
    Partial<Pick<StartupMaster, "corporationNumber">>,
): StartupMaster {
  return {
    corporationNumber: null,
    ...partial,
    normalizedName: normalizeCompanyName(partial.name),
  };
}

function expert(partial: Omit<ExpertMaster, "normalizedName">): ExpertMaster {
  return { ...partial, normalizedName: normalizeCompanyName(partial.name) };
}

function partner(partial: Omit<PartnerMaster, "normalizedName">): PartnerMaster {
  return { ...partial, normalizedName: normalizeCompanyName(partial.name) };
}

export function seedStartups(): StartupMaster[] {
  return [
    startup({
      id: "st-1",
      masterCode: "YNA-ST-2026-0001",
      name: "알파테크",
      legalName: "주식회사 알파테크",
      businessNumber: "1234567890",
      corporationNumber: "110111-1234567",
      representativeName: "홍길동",
      phone: "01012345678",
      email: "contact@alpha.example",
      websiteUrl: "https://alpha.example",
      address: "서울특별시 강남구 테헤란로 1",
      industry: "SaaS",
      stage: "Series A",
      sourceDomain: "work",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-03-01T02:00:00Z",
      updatedAt: "2026-06-20T05:00:00Z",
    }),
    startup({
      id: "st-2",
      masterCode: "YNA-ST-2026-0002",
      name: "베타솔루션",
      legalName: "베타솔루션 주식회사",
      businessNumber: "2233445566",
      corporationNumber: null,
      representativeName: "김영희",
      phone: "01033334444",
      email: "hello@beta.example",
      websiteUrl: null,
      address: "부산광역시 해운대구 센텀로 99",
      industry: "물류",
      stage: "Seed",
      sourceDomain: "fund",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-03-05T02:00:00Z",
      updatedAt: "2026-05-01T05:00:00Z",
    }),
    startup({
      id: "st-3",
      masterCode: "YNA-ST-2026-0003",
      name: "감마랩스",
      legalName: null,
      businessNumber: null,
      representativeName: "이철수",
      phone: "01055556666",
      email: null,
      websiteUrl: "https://gamma.example",
      address: null,
      industry: "바이오",
      stage: "예비창업",
      sourceDomain: "work",
      verificationStatus: "needs_review",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-04-10T02:00:00Z",
      updatedAt: "2026-04-10T02:00:00Z",
    }),
    startup({
      id: "st-4",
      masterCode: "YNA-ST-2026-0004",
      name: "델타모빌리티",
      legalName: "델타모빌리티 주식회사",
      businessNumber: "5566778899",
      representativeName: "박민수",
      phone: "01077778888",
      email: "info@delta.example",
      websiteUrl: null,
      address: "대전광역시 유성구 대학로 291",
      industry: "모빌리티",
      stage: "Series B",
      sourceDomain: "mna",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-02-01T02:00:00Z",
      updatedAt: "2026-06-01T05:00:00Z",
    }),
    startup({
      id: "st-old",
      masterCode: "YNA-ST-2026-0009",
      name: "알파테크(구)",
      legalName: null,
      businessNumber: null,
      representativeName: "홍길동",
      phone: "01012345678",
      email: null,
      websiteUrl: null,
      address: null,
      industry: null,
      stage: null,
      sourceDomain: "work",
      verificationStatus: "verified",
      status: "merged",
      mergedIntoId: "st-1",
      createdAt: "2026-01-15T02:00:00Z",
      updatedAt: "2026-06-18T05:00:00Z",
    }),
    startup({
      id: "st-temp",
      masterCode: "TEMP-ST-2026-0092",
      name: "알파",
      legalName: null,
      businessNumber: null,
      representativeName: "홍길동",
      phone: "01012345678",
      email: "hong@alpha.example",
      websiteUrl: null,
      address: null,
      industry: null,
      stage: "예비창업",
      sourceDomain: "work",
      verificationStatus: "temporary",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-07-01T02:00:00Z",
      updatedAt: "2026-07-01T02:00:00Z",
    }),
  ];
}

export function seedExperts(): ExpertMaster[] {
  return [
    expert({
      id: "ex-1",
      masterCode: "YNA-EX-2026-0001",
      name: "홍멘토",
      email: "hong.mentor@expert.example",
      phone: "01023450001",
      organization: "알파벤처스",
      position: "대표 파트너",
      expertiseTags: ["SaaS", "핀테크", "IR"],
      sourceDomain: "work",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-03-02T02:00:00Z",
      updatedAt: "2026-06-10T05:00:00Z",
    }),
    expert({
      id: "ex-2",
      masterCode: "YNA-EX-2026-0002",
      name: "김전문",
      email: "kim.pro@expert.example",
      phone: "01023450002",
      organization: "스마트법무법인",
      position: "변호사",
      expertiseTags: ["법률", "지식재산"],
      sourceDomain: "work",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-03-12T02:00:00Z",
      updatedAt: "2026-05-20T05:00:00Z",
    }),
    // 동명이인 예시: 이름만으로 자동 병합하지 않음(functional_spec §8 완료 기준).
    expert({
      id: "ex-3",
      masterCode: "YNA-EX-2026-0003",
      name: "이심사",
      email: "lee.audit.a@expert.example",
      phone: "01023450003",
      organization: "한국기술평가원",
      position: "책임연구원",
      expertiseTags: ["기술평가", "바이오"],
      sourceDomain: "fund",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-04-01T02:00:00Z",
      updatedAt: "2026-06-02T05:00:00Z",
    }),
    expert({
      id: "ex-9",
      masterCode: "YNA-EX-2026-0009",
      name: "이심사",
      email: "lee.audit.b@expert.example",
      phone: "01023450009",
      organization: "성장금융투자",
      position: "심사역",
      expertiseTags: ["투자심사"],
      sourceDomain: "work",
      verificationStatus: "pending",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-06-30T02:00:00Z",
      updatedAt: "2026-06-30T02:00:00Z",
    }),
  ];
}

export function seedPartners(): PartnerMaster[] {
  return [
    partner({
      id: "pt-1",
      masterCode: "YNA-PT-2026-0001",
      name: "한국벤처투자",
      partnerType: "lp",
      businessNumber: "3011200123",
      representativeName: "정대표",
      phone: "0221000000",
      email: "contact@kvic.example",
      websiteUrl: "https://kvic.example",
      address: "서울특별시 강남구 테헤란로 500",
      sourceDomain: "fund",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-02-10T02:00:00Z",
      updatedAt: "2026-06-05T05:00:00Z",
    }),
    partner({
      id: "pt-2",
      masterCode: "YNA-PT-2026-0002",
      name: "스마트법무법인",
      partnerType: "advisor",
      businessNumber: "1078812345",
      representativeName: "김전문",
      phone: "0255511234",
      email: "office@smartlaw.example",
      websiteUrl: null,
      address: "서울특별시 서초구 서초대로 200",
      sourceDomain: "mna",
      verificationStatus: "verified",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-03-01T02:00:00Z",
      updatedAt: "2026-05-15T05:00:00Z",
    }),
    partner({
      id: "pt-3",
      masterCode: "YNA-PT-2026-0003",
      name: "창업진흥원",
      partnerType: "operator",
      businessNumber: null,
      representativeName: "박원장",
      phone: "0424100000",
      email: null,
      websiteUrl: "https://kised.example",
      address: "대전광역시 중구 대종로 480",
      sourceDomain: "work",
      verificationStatus: "needs_review",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-04-20T02:00:00Z",
      updatedAt: "2026-04-20T02:00:00Z",
    }),
    // 사업자번호 일치 중복 후보 예시(functional_spec §9 완료 기준).
    partner({
      id: "pt-temp",
      masterCode: "TEMP-PT-2026-0044",
      name: "스마트 법무",
      partnerType: "advisor",
      businessNumber: "1078812345",
      representativeName: "김전문",
      phone: null,
      email: null,
      websiteUrl: null,
      address: null,
      sourceDomain: "mna",
      verificationStatus: "temporary",
      status: "active",
      mergedIntoId: null,
      createdAt: "2026-06-29T02:00:00Z",
      updatedAt: "2026-06-29T02:00:00Z",
    }),
  ];
}
